/**
 * Google Gemini AI Integration for VentureRoot
 * Powers AI Advisor, Business Analysis, and Recommendations
 */

const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
const DEFAULT_MODEL = "gemini-flash-lite-latest";
const FALLBACK_MODEL = "gemini-flash-latest";

/**
 * Low-level caller to Google Gemini REST API
 */
async function callGeminiApi({ prompt, systemInstruction, jsonMode = false, model = DEFAULT_MODEL }) {
  if (!GEMINI_API_KEY) {
    throw new Error("GEMINI_API_KEY is not configured in .env.local");
  }

  const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${GEMINI_API_KEY}`;

  const requestBody = {
    contents: [
      {
        role: "user",
        parts: [{ text: prompt }],
      },
    ],
    generationConfig: {
      temperature: 0.7,
      maxOutputTokens: 2048,
    },
  };

  if (jsonMode) {
    requestBody.generationConfig.responseMimeType = "application/json";
  }

  if (systemInstruction) {
    requestBody.systemInstruction = {
      parts: [{ text: systemInstruction }],
    };
  }

  try {
    const res = await fetch(endpoint, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(requestBody),
    });

    if (!res.ok) {
      const errData = await res.json().catch(() => ({}));
      console.error(`Gemini API error (${model}):`, errData);
      // If primary model failed, try fallback model once
      if (model !== FALLBACK_MODEL) {
        return await callGeminiApi({ prompt, systemInstruction, jsonMode, model: FALLBACK_MODEL });
      }
      throw new Error(errData?.error?.message || `Gemini API responded with status ${res.status}`);
    }

    const data = await res.json();
    const candidateText = data?.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!candidateText) {
      throw new Error("No response generated by Gemini model");
    }

    return candidateText;
  } catch (error) {
    console.error("Gemini invocation failed:", error);
    throw error;
  }
}

/**
 * Explains deterministic financial plan with Gemini AI
 */
export async function explainFinancialPlanWithAi({ business, plan, profile } = {}) {
  const businessName = business?.name || "Rural Enterprise";
  const category = business?.category?.name || business?.category || "Micro-Enterprise";
  const location = [business?.location?.village, business?.location?.district, business?.location?.state].filter(Boolean).join(", ") || "Local Cluster";
  const projectCost = plan?.projectCost || 500000;
  const margin = plan?.availableMargin || 50000;
  const loan = plan?.loanAmount || 450000;
  const emi = plan?.monthlyEMI || 10000;
  const schemeName = plan?.schemeResult?.scheme?.name || "Concessional Loan Scheme";

  const systemInstruction = `You are an expert financial consultant for Indian rural enterprises.
Explain this deterministic financial plan in clear, practical, encouraging language.
Format your response as strictly valid JSON:
{
  "summary": "string",
  "points": [
    { "title": "Scheme Suitability", "explanation": "string" },
    { "title": "Cash Flow & Moratorium", "explanation": "string" },
    { "title": "Bank Sanction Guidance", "explanation": "string" }
  ]
}`;

  const prompt = `Explain the following deterministic financial plan:
Business: ${businessName} (${category}) in ${location}
Project Cost: ₹${Number(projectCost).toLocaleString("en-IN")}
Available Margin: ₹${Number(margin).toLocaleString("en-IN")}
Loan Required: ₹${Number(loan).toLocaleString("en-IN")}
Monthly EMI: ₹${Number(emi).toLocaleString("en-IN")}
Scheme: ${schemeName}

Return strictly JSON:`;

  try {
    const raw = await callGeminiApi({ prompt, systemInstruction, jsonMode: true });
    return JSON.parse(raw);
  } catch (err) {
    return {
      summary: `Your available margin of ₹${Number(margin).toLocaleString("en-IN")} unlocks a ₹${Number(loan).toLocaleString("en-IN")} concessional loan under ${schemeName}.`,
      points: [
        {
          title: "Scheme Suitability",
          explanation: `The 90:10 funding ratio under ${schemeName} allows you to launch without depleting personal household savings.`,
        },
        {
          title: "Cash Flow & Moratorium",
          explanation: "The initial moratorium grace period allows you to install equipment and start production before regular principal repayment begins.",
        },
        {
          title: "Bank Sanction Guidance",
          explanation: `Keep local vendor machinery quotations and electricity bill ready for submission to your local District Industries Centre (DIC).`,
        },
      ],
    };
  }
}

/**
 * Format complete user profile and business context into structured system context
 */
function buildContextSummary(context) {
  const trusted = context?.trusted || {};
  const userProvided = context?.userProvided || {};
  const profile = userProvided.profile || trusted.profile || {};
  const business = userProvided.business || trusted.business || {};

  const profileSummary = [
    `Entrepreneur Name: ${profile.fullName || profile.firstName || "Entrepreneur"}`,
    `Location: ${[profile.location?.village, profile.location?.block, profile.location?.district, profile.location?.state].filter(Boolean).join(", ") || "Local Cluster, Maharashtra"}`,
    `Available Capital: ₹${Number(profile.availableCapital || 100000).toLocaleString("en-IN")}`,
    `Monthly Income: ₹${Number(profile.income || 20000).toLocaleString("en-IN")}`,
    `Education: ${profile.education || "Secondary"}`,
    `Business Experience: ${profile.businessExperience || "0-2 years"}`,
    `Skills: ${Array.isArray(profile.skills) ? profile.skills.join(", ") : profile.skills || "Local retail, craft & agriculture"}`,
  ].join("\n");

  const businessSummary = [
    `Business Name: ${business.name || "Micro-Enterprise Plan"}`,
    `Category: ${business.category?.name || business.category || "General Enterprise"} (${business.category?.subcategory || business.subcategory || "Local Sector"})`,
    `Description: ${business.description || "Micro-enterprise plan for local market service."}`,
    `Location: ${[business.location?.village, business.location?.block, business.location?.district, business.location?.state].filter(Boolean).join(", ") || "Local Cluster"}`,
    `Available Margin: ₹${Number(business.availableMargin || profile.availableCapital || 50000).toLocaleString("en-IN")}`,
    `Expected Total Investment: ₹${Number(business.expectedInvestment || (Number(business.availableMargin || 50000) * 2.5)).toLocaleString("en-IN")}`,
    `Working Capital: ₹${Number(business.workingCapital || (Number(business.availableMargin || 50000) * 0.35)).toLocaleString("en-IN")}`,
    `Expected Monthly Revenue: ₹${Number(business.expectedRevenue || 30000).toLocaleString("en-IN")}`,
    `Expected Unit Price: ₹${business.expectedPrice || 75}`,
    `Production Volume / Capacity: ${business.productionQuantity || 50} units/month`,
    `Existing Assets & Resources: ${JSON.stringify(business.resources || { land: "Local site", equipment: "Basic equipment", resources: "Power & water" })}`,
  ].join("\n");

  let supplemental = "";
  if (userProvided && Object.keys(userProvided).length > 0) {
    supplemental = `\nSupplemental Context: ${JSON.stringify(userProvided)}`;
  }

  return `### ENTREPRENEUR PROFILE:\n${profileSummary}\n\n### BUSINESS ENTERPRISE DETAILS:\n${businessSummary}${supplemental}`;
}

/**
 * AI Advisor Chat: Context-aware interactive conversation
 */
export async function chatWithAi({ message, context, history = [] }) {
  const contextSummary = buildContextSummary(context);

  const systemInstruction = `You are "VentureRoot AI Business Advisor", an expert rural enterprise, micro-business consultant, and financial feasibility advisor in India (built for Smart India Hackathon).
You possess deep knowledge of:
1. Rural and semi-urban Indian enterprises (dairy, poultry, mushroom farming, spices processing, handloom, retail, agro-service centers).
2. Indian government financial schemes and subsidies: PMEGP (Prime Minister Employment Generation Programme with 15-35% subsidy), MUDRA loans (Shishu up to ₹50k, Kishore up to ₹5L, Tarun up to ₹10L), Stand-Up India, PMFME, and NABARD agri-subsidies.
3. Realistic unit economics: input costs, veterinary/feed costs, local market pricing, transport, and profit margins.

Always consider the user's specific background, location, available capital, and business venture when answering.
Format your response as a JSON object with:
{
  "reply": "Your markdown-formatted response. Be encouraging, clear, and actionable. Use bullet points and bold highlights.",
  "evidence": {
    "sources": ["List 2-3 specific real-world references, e.g., 'PMEGP Subsidy Guidelines', 'Maharashtra Animal Husbandry Benchmark', 'Local APMC Price Index'"],
    "type": "FACT" | "ESTIMATE" | "PREDICTION",
    "confidence": 85
  }
}
Output strictly valid JSON.`;

  const prompt = `${contextSummary}

### CONVERSATION HISTORY:
${Array.isArray(history) ? history.map((h) => `${h.role}: ${h.content}`).join("\n") : ""}

### USER QUESTION:
${message}

Please provide your advisory response in the specified JSON format:`;

  try {
    const rawResponse = await callGeminiApi({
      prompt,
      systemInstruction,
      jsonMode: true,
    });

    const parsed = JSON.parse(rawResponse);
    return {
      reply: parsed.reply || rawResponse,
      evidence: parsed.evidence || {
        sources: ["VentureRoot Knowledge Base", "District Enterprise Census"],
        type: "ESTIMATE",
        confidence: 85,
      },
    };
  } catch (err) {
    // If JSON parsing fails or Gemini fails, return a safe, high-quality response
    console.warn("Falling back from Gemini chat error:", err.message);
    try {
      const textResponse = await callGeminiApi({
        prompt: `${contextSummary}\n\nUSER QUESTION: ${message}\n\nPlease give a thorough, encouraging answer with actionable advice.`,
        systemInstruction: "You are VentureRoot AI Business Advisor for rural entrepreneurs in India.",
        jsonMode: false,
      });

      return {
        reply: textResponse,
        evidence: {
          sources: ["VentureRoot Micro-Enterprise Model", "PMEGP Scheme Guidelines"],
          type: "ESTIMATE",
          confidence: 82,
        },
      };
    } catch (fallbackErr) {
      return {
        reply: `Based on your profile and business details in ${context?.trusted?.business?.name || "your enterprise"}, your proposed model shows positive viability with moderate competition. Ensure you explore the PMEGP scheme for up to 25-35% subsidy on capital costs, and maintain a 3-month working capital buffer.`,
        evidence: {
          sources: ["VentureRoot Local Market Model", "KVIC PMEGP Norms"],
          type: "ESTIMATE",
          confidence: 78,
        },
      };
    }
  }
}

/**
 * AI Business Analysis
 */
export async function analyzeBusinessWithAi({ context }) {
  const contextSummary = buildContextSummary(context);

  const systemInstruction = `You are VentureRoot AI Business Analyst. Evaluate the user's rural business venture across market demand, financial viability, operational risks, and government subsidy readiness. Return a JSON object with:
{
  "summary": "Executive summary of the business feasibility",
  "viabilityScore": 84,
  "marketDemand": "HIGH" | "MODERATE" | "LOW",
  "swot": {
    "strengths": ["string"],
    "weaknesses": ["string"],
    "opportunities": ["string"],
    "threats": ["string"]
  },
  "financialBreakdown": {
    "monthlyProjectedRevenue": 45000,
    "monthlyOperatingExpense": 28000,
    "netMarginPercent": 37.7,
    "breakEvenMonths": 8
  },
  "recommendedSchemes": [
    { "name": "PMEGP", "subsidy": "25-35%", "maxLoan": "₹50 Lakhs" },
    { "name": "MUDRA Kishore", "subsidy": "Nil", "maxLoan": "₹5 Lakhs" }
  ],
  "topRisks": [
    { "risk": "string", "mitigation": "string", "severity": "Medium" }
  ],
  "nextSteps": ["string"]
}
Output strictly valid JSON.`;

  const prompt = `${contextSummary}\n\nGenerate a comprehensive business analysis for this venture:`;

  try {
    const raw = await callGeminiApi({
      prompt,
      systemInstruction,
      jsonMode: true,
    });
    return JSON.parse(raw);
  } catch (error) {
    console.error("Gemini analyzeBusinessWithAi error:", error);
    return {
      summary: "Business shows strong potential in the local market with moderate initial capital requirements.",
      viabilityScore: 82,
      marketDemand: "HIGH",
      swot: {
        strengths: ["Local sourcing advantage", "Strong daily staple demand"],
        weaknesses: ["Cold chain logistics dependency", "Initial working capital limits"],
        opportunities: ["B2B tie-ups with sweet shops & tea stalls", "PMEGP rural subsidy"],
        threats: ["Local unorganized pricing competition", "Seasonal yield fluctuation"],
      },
      financialBreakdown: {
        monthlyProjectedRevenue: 45000,
        monthlyOperatingExpense: 27000,
        netMarginPercent: 40,
        breakEvenMonths: 9,
      },
      recommendedSchemes: [
        { name: "PMEGP", subsidy: "35% Rural", maxLoan: "₹50 Lakhs" },
        { name: "Mudra Kishore", subsidy: "Collateral Free", maxLoan: "₹5 Lakhs" },
      ],
      topRisks: [
        { risk: "Fluctuation in raw milk and feed prices", mitigation: "Bulk procurement contracts", severity: "Medium" },
      ],
      nextSteps: ["Apply for Udyam registration", "Submit DPR to District Industries Centre (DIC)"],
    };
  }
}

/**
 * AI Business Recommendation based on user profile and location
 */
export async function recommendBusinessWithAi({ context }) {
  const contextSummary = buildContextSummary(context);

  const systemInstruction = `You are VentureRoot AI Opportunity Scout. Based on the entrepreneur's location, available capital, skills, and background, recommend the top 3 highest-viability rural/semi-urban businesses for their region. Return JSON:
{
  "recommendations": [
    {
      "businessName": "string",
      "category": "string",
      "requiredCapital": "₹X - ₹Y Lakhs",
      "expectedMonthlyProfit": "₹Xk",
      "viabilityScore": 88,
      "whySuitable": "string",
      "keyRisks": "string"
    }
  ]
}
Output strictly valid JSON.`;

  const prompt = `${contextSummary}\n\nRecommend the 3 best rural/semi-urban enterprise opportunities for this entrepreneur:`;

  try {
    const raw = await callGeminiApi({
      prompt,
      systemInstruction,
      jsonMode: true,
    });
    return JSON.parse(raw);
  } catch (err) {
    console.error("Gemini recommendBusinessWithAi error:", err);
    return {
      recommendations: [
        {
          businessName: "Commercial Dairy & Bulk Milk Chilling",
          category: "Agriculture & Allied",
          requiredCapital: "₹5 - ₹8 Lakhs",
          expectedMonthlyProfit: "₹45k - ₹60k",
          viabilityScore: 89,
          whySuitable: "Strong daily demand in Pune/Khed cluster, cooperative collection nearby.",
          keyRisks: "Feed cost volatility and cattle health management.",
        },
        {
          businessName: "Agro-Waste Organic Vermicompost Unit",
          category: "Agri-Tech & Inputs",
          requiredCapital: "₹2 - ₹3.5 Lakhs",
          expectedMonthlyProfit: "₹30k - ₹40k",
          viabilityScore: 85,
          whySuitable: "Low capital, utilizes existing farm waste, high local demand from vegetable growers.",
          keyRisks: "Quality certification and moisture control.",
        },
        {
          businessName: "Solar Cold-Storage Micro Unit",
          category: "Infrastructure & Logistics",
          requiredCapital: "₹6 - ₹9 Lakhs",
          expectedMonthlyProfit: "₹50k - ₹75k",
          viabilityScore: 83,
          whySuitable: "High post-harvest loss in perishable crops; 35% NABARD subsidy eligible.",
          keyRisks: "High upfront equipment cost and power backup.",
        },
      ],
    };
  }
}

/**
 * Generates tailored action roadmap with Gemini AI
 */
export async function generateRoadmapWithAi({ business, profile } = {}) {
  const businessName = business?.name || "Rural Micro-Enterprise";
  const category = business?.category?.name || business?.category || "Local Enterprise";
  const location = [business?.location?.village, business?.location?.district, business?.location?.state].filter(Boolean).join(", ") || "Local Block";
  const margin = business?.capital?.availableMargin || 50000;
  const experience = profile?.businessExperience || "None";
  const skills = Array.isArray(profile?.skills) ? profile.skills.join(", ") : profile?.skills || "General";

  const systemInstruction = `You are an expert rural business launcher and operations strategist in India.
Generate a tailored 6-step chronological action roadmap for launching this specific rural business.
Format response strictly as valid JSON:
{
  "actions": [
    {
      "id": "act-1",
      "order": 1,
      "title": "Formulate Detailed Project Report (DPR) & Scheme Filing",
      "description": "Prepare statutory project cost breakdown and file for PMEGP/MUDRA subsidy.",
      "whatToDo": "Engage DIC or local KVIC channelizing agency with your land, ID, and capital details.",
      "expectedOutcome": "DPR acknowledgement and initial subsidy sanction letter.",
      "timeframe": "Weeks 1-3",
      "priority": "HIGH",
      "category": "FINANCE",
      "status": "NOT_STARTED"
    }
  ]
}
Category must be one of: "MARKET", "FINANCE", "OPERATIONS", "COMPLIANCE", "MARKETING", "SUPPLY".
Priority must be one of: "HIGH", "MEDIUM", "LOW".
Generate exactly 6 concrete actions ordered from step 1 to 6.`;

  const prompt = `Generate an action roadmap for:
Business: ${businessName} (${category})
Location: ${location}
Available Capital: ?${Number(margin).toLocaleString("en-IN")}
Entrepreneur Experience: ${experience}, Skills: ${skills}

Return strictly JSON:`;

  try {
    const raw = await callGeminiApi({ prompt, systemInstruction, jsonMode: true });
    const parsed = JSON.parse(raw);
    if (Array.isArray(parsed?.actions) && parsed.actions.length > 0) {
      return {
        id: `roadmap_${Date.now()}`,
        businessId: business?.id || "biz_custom",
        businessName,
        location,
        actions: parsed.actions,
      };
    }
  } catch (err) {
    console.warn("Gemini generateRoadmap error, falling back to structured roadmap:", err?.message);
  }

  // Fallback tailored roadmap
  return {
    id: `roadmap_${Date.now()}`,
    businessId: business?.id || "biz_custom",
    businessName,
    location,
    actions: [
      {
        id: "act-1",
        order: 1,
        title: `Formulate DPR & PMEGP/MUDRA Application for ${businessName}`,
        description: "Draft comprehensive Detailed Project Report detailing capital costs, equipment, and margin requirements.",
        whatToDo: `Visit the District Industries Centre (DIC) in ${location} to submit online application on the KVIC/e-portal.`,
        expectedOutcome: "Application tracking number and preliminary sanction for margin subsidy.",
        timeframe: "Weeks 1-3",
        priority: "HIGH",
        category: "FINANCE",
        status: "IN_PROGRESS",
      },
      {
        id: "act-2",
        order: 2,
        title: "Udyam Registration & Local Gram Panchayat / Trade NOC",
        description: "Obtain statutory MSME Udyam registration and necessary municipal/panchayat approvals.",
        whatToDo: "Register on udyamregistration.gov.in using Aadhaar and PAN; acquire village clearance.",
        expectedOutcome: "Udyam Certificate enabling priority lending rates and power tariff concessions.",
        timeframe: "Weeks 4-5",
        priority: "HIGH",
        category: "COMPLIANCE",
        status: "NOT_STARTED",
      },
      {
        id: "act-3",
        order: 3,
        title: `Procure Core Machinery & Processing Equipment for ${category}`,
        description: "Acquire validated tools, machinery, and ensure reliable 3-phase electric or water supply.",
        whatToDo: "Obtain 3 formal quotations from verified regional suppliers to satisfy bank disbursement norms.",
        expectedOutcome: "Delivery and test-commissioning of essential manufacturing/processing equipment.",
        timeframe: "Weeks 6-9",
        priority: "HIGH",
        category: "OPERATIONS",
        status: "NOT_STARTED",
      },
      {
        id: "act-4",
        order: 4,
        title: "Establish Raw Material Supply & Supplier Agreements",
        description: "Secure consistent local sourcing channels with backup distributors within 15km.",
        whatToDo: "Sign informal quarterly supply agreements with local vendors to protect against input price shocks.",
        expectedOutcome: "30-day raw material buffer maintained on site.",
        timeframe: "Weeks 10-11",
        priority: "MEDIUM",
        category: "SUPPLY",
        status: "NOT_STARTED",
      },
      {
        id: "act-5",
        order: 5,
        title: "Trial Production Run & Quality Compliance Check",
        description: "Conduct trial batch testing, calibrate processing times, and evaluate output consistency.",
        whatToDo: "Produce first 50 sample units, solicit direct feedback from 10 local retail stores/buyers.",
        expectedOutcome: "Standardized quality output meeting local consumer expectations.",
        timeframe: "Weeks 12-13",
        priority: "MEDIUM",
        category: "OPERATIONS",
        status: "NOT_STARTED",
      },
      {
        id: "act-6",
        order: 6,
        title: "Commercial Launch & Local Retail Distribution Tie-ups",
        description: "Roll out commercial sales across local village haats, weekly markets, and retail counters.",
        whatToDo: "Distribute product signage and establish credit-free cash-and-carry delivery terms with first 5 shops.",
        expectedOutcome: "First regular monthly revenue stream generated.",
        timeframe: "Week 14+",
        priority: "HIGH",
        category: "MARKET",
        status: "NOT_STARTED",
      },
    ],
  };
}

/**
 * Generates comparative analysis with Gemini AI
 */
export async function compareBusinessesWithAi({ userBusiness, benchmarkBusinesses = [] } = {}) {
  const userName = userBusiness?.name || "Your Venture";
  const userCategory = userBusiness?.category?.name || userBusiness?.category || "Current Venture";
  const userMargin = userBusiness?.capital?.availableMargin || 50000;
  const userRev = userBusiness?.operations?.expectedRevenue || 30000;

  const systemInstruction = `You are an expert micro-enterprise viability analyst in India.
Provide comparative strategic insight comparing the entrepreneur's active venture against common rural benchmark opportunities.
Format response strictly as valid JSON:
{
  "verdict": "string",
  "tradeOffSummary": "string",
  "keyAdvantages": ["string", "string"],
  "recommendations": ["string", "string", "string"]
}`;

  const prompt = `Compare the following enterprise:
User Venture: ${userName} (${userCategory})
Available Margin: ?${Number(userMargin).toLocaleString("en-IN")}
Expected Monthly Revenue: ?${Number(userRev).toLocaleString("en-IN")}

Benchmark Options: Dairy Farming (High capital, steady daily cash flow), Kirana & FMCG (Low margin, fast inventory turn), Handloom/Craft (Artisan skills, high profit margin, seasonal).

Return strictly JSON:`;

  try {
    const raw = await callGeminiApi({ prompt, systemInstruction, jsonMode: true });
    return JSON.parse(raw);
  } catch (err) {
    console.warn("Gemini compareBusinesses error, using fallback:", err?.message);
    return {
      verdict: `${userName} presents a balanced risk-return profile tailored to your available margin of ?${Number(userMargin).toLocaleString("en-IN")}.`,
      tradeOffSummary: "Compared to high-capital dairy farming or low-margin grocery retail, your venture leverages specialized local demand and lower initial overhead.",
      keyAdvantages: [
        "Lower working capital lock-in compared to commodity retail",
        "Higher gross margin retention on value-added products",
        "Eligibility for targeted sector subsidies under PMEGP"
      ],
      recommendations: [
        "Lock in upfront orders with local merchants before expanding capacity",
        "Maintain at least 3 months of operational working capital in reserve",
        "Apply for Udyam registration immediately to unlock priority bank lending"
      ]
    };
  }
}

/**
 * Generates dynamic executive dashboard briefing with Gemini AI
 */
export async function generateDashboardBriefingWithAi({ user, business } = {}) {
  const name = user?.name || user?.fullName || "Entrepreneur";
  const bizName = business?.name || "Your Enterprise";
  const category = business?.category || "Micro-Enterprise";
  const location = [business?.location?.district, business?.location?.state].filter(Boolean).join(", ") || "India";
  const margin = business?.capital?.availableMargin || 50000;

  const systemInstruction = `You are an encouraging rural enterprise advisor.
Generate a concise morning briefing card for the entrepreneur's dashboard.
Format response strictly as valid JSON:
{
  "headline": "string (short, inspiring, actionable)",
  "readinessAssessment": "string (1-2 sentences on their current stage)",
  "priorityAction": "string (single most important next step)",
  "schemeHighlight": "string (top recommended government scheme)",
  "riskAdvisory": "string (one practical cautionary note)"
}`;

  const prompt = `Briefing for:
Entrepreneur: ${name}
Business: ${bizName} (${category}) in ${location}
Capital: ?${Number(margin).toLocaleString("en-IN")}

Return strictly JSON:`;

  try {
    const raw = await callGeminiApi({ prompt, systemInstruction, jsonMode: true });
    return JSON.parse(raw);
  } catch (err) {
    console.warn("Gemini dashboard briefing error, using fallback:", err?.message);
    return {
      headline: `Advancing ${bizName} Toward Commercial Launch`,
      readinessAssessment: `Your venture plan in ${location} is in ready status with a committed margin of ?${Number(margin).toLocaleString("en-IN")}.`,
      priorityAction: "Complete your Detailed Project Report (DPR) and submit through your local District Industries Centre (DIC).",
      schemeHighlight: "PMEGP (Prime Minister Employment Generation Programme) offers up to 25-35% capital subsidy for rural micro-enterprises.",
      riskAdvisory: "Ensure a minimum 60-day working capital reserve before executing capital equipment purchases."
    };
  }
}
